### ISSUE TITLE
with the latest release of azure-storage-blob 12.0.0, seldon build fails

### ISSUE THREAD

**Issue by klalit** [SeldonIO/seldon-core#1027]
earlier the version was azure-storage-blob 2.1.0 but with latest release on Oct-31-2019. Seldon has a dependency on azure-storage-blob >=2.1.0, the following error is thrown

>>> from azure.storage.blob import BlockBlobService
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BlockBlobService'

**Comment by cliveseldon** [comment]
Should be fixed in https://pypi.org/project/seldon-core/0.5.0.2/

**Comment by klalit** [comment]
one thought... can't we fix the versions in requirements.txt to avoid these kind of scenarios in future..

**Comment by axsaucedo** [comment]
Yeah we were discussing this earlier, but we also didn't want to restrict the setup.py dependencies too much as otherwise it can easily clash when other dependencies are brought in (i.e currently Seldon Core works with TF 2.0, we wouldn't want to restrict installations unless they break). We could do this for some dependencies but we'd want to be careful with making it too restrictive...

Specifically on this, we are looking to reduce our dependencies, and specifically on the libraries to access object stores (an other files) we are looking to potentially remove the dependency on Storage.py and use an external library such as Apache Libcloud, wchih is currently being discussed in #885.

@klalit it would be great to hear your thoughts on #885, primarily as this is something that will be driven by what people use most often to download files.

**Comment by axsaucedo** [comment]
@klalit I am closing all other issues and opening just this one #1028 to evaluate what options we can take for this.

**Comment by klalit** [comment]
@axsaucedo yes we may close this one if another ticket already consolidates similar issues.
