### PR TITLE
add note on SO_REUSEPORT requirement

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

Add note on `AttributeError: module 'socket' has no attribute 'SO_REUSEPORT'` to the upgrading page.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

- The issue is present on specific Python distributions: https://community.intel.com/t5/Intel-Distribution-for-Python/AttributeError-module-socket-has-no-attribute-SO-REUSEPORT/m-p/1257361/highlight/true
- PR that introduced the requirement SeldonIO/seldon-core#3356 

Difficult to establish universal minimum version requirements. For example for 3.8.x line it does not work with <3.8.5, works fine with 3.8.5 and 3.8.6. Couldn't test with 3.8.7 as there was no anaconda package, then was broken for 3.8.8 and fixed again for 3.8.10 for example. But this can actually lie in the compilation problem of the python itself so version compatibility is difficult to establish.

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
